### ISSUE TITLE
Unable to request list organizations

### ISSUE THREAD

**Issue by ronzyfonzy** [space-invoices/si-api-js-sdk#2]
I [modified](https://github.com/ronzyfonzy/si-api-js-sdk/commit/8ab51a43cd06167b966577c21f1aba934320d8be?diff=unified) the organizations model to support **list** method. When I tested it the app gave me the error bellow:
```
{ Internal Server Error: 500 - {"error":{"statusCode":500,"name":"TypeError","message":"Cannot read property 'filter' of null","stack":"TypeError: Cannot read property 'filter' of null\n    at HttpContext.getArgByName (/usr/src/app/node_modules/strong-remoting/lib/http-context.js:231:66)\n    at HttpContext.buildArgs (/usr/src/app/node_modules/strong-remoting/lib/http-context.js:183:17)\n    at new HttpContext (/usr/src/app/node_modules/strong-remoting/lib/http-context.js:59:20)\n    at restPrototypeMethodHandler (/usr/src/app/node_modules/strong-remoting/lib/rest-adapter.js:495:15)\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)\n
at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at /usr/src/app/node_modules/express/lib/router/index.js:281:22\n    at param (/usr/src/app/node_modules/express/lib/router/index.js:354:14)\n    at param (/usr/src/app/node_modules/express/lib/router/index.js:365:14)\n    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:410:3)\n    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)\n    at Function.handle (/usr/src/app/node_modules/express/lib/router/index.js:174:3)\n    at router (/usr/src/app/node_modules/express/lib/router/index.js:47:12)\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)\n    at /usr/src/app/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)\n    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)\n    at /usr/src/app/node_modules/body-parser/lib/read.js:130:5\n
  at invokeCallback (/usr/src/app/node_modules/raw-body/index.js:224:16)\n    at done (/usr/src/app/node_modules/raw-body/index.js:213:7)\n
at IncomingMessage.onEnd (/usr/src/app/node_modules/raw-body/index.js:273:7)\n    at emitNone (events.js:86:13)\n    at IncomingMessage.emit (events.js:188:7)\n    at endReadableNT (_stream_readable.js:975:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at
process._tickDomainCallback (internal/process/next_tick.js:128:9)"}}
    at errorHandler (C:\Users\Ronzy\Development\personal\si-api-js-sdk\lib\requestService.js:49:13)
    at C:\Users\Ronzy\Development\personal\si-api-js-sdk\lib\requestService.js:38:14
    at tryCatcher (C:\Users\Ronzy\Development\personal\si-api-js-sdk\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Ronzy\Development\personal\si-api-js-sdk\node_modules\bluebird\js\release\promise.js:512:31)    at Promise._settlePromise (C:\Users\Ronzy\Development\personal\si-api-js-sdk\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Ronzy\Development\personal\si-api-js-sdk\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Ronzy\Development\personal\si-api-js-sdk\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (C:\Users\Ronzy\Development\personal\si-api-js-sdk\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Ronzy\Development\personal\si-api-js-sdk\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Ronzy\Development\personal\si-api-js-sdk\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
  name: 'Internal Server Error',
  text: 'We had a problem with our server. Try again later.',
  message: '500 - {"error":{"statusCode":500,"name":"TypeError","message":"Cannot read property \'filter\' of null","stack":"TypeError: Cannot
read property \'filter\' of null\\n    at HttpContext.getArgByName (/usr/src/app/node_modules/strong-remoting/lib/http-context.js:231:66)\\n
 at HttpContext.buildArgs (/usr/src/app/node_modules/strong-remoting/lib/http-context.js:183:17)\\n    at new HttpContext (/usr/src/app/node_modules/strong-remoting/lib/http-context.js:59:20)\\n    at restPrototypeMethodHandler (/usr/src/app/node_modules/strong-remoting/lib/rest-adapter.js:495:15)\\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\\n    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)\\n    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)\\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\\n    at /usr/src/app/node_modules/express/lib/router/index.js:281:22\\n    at param (/usr/src/app/node_modules/express/lib/router/index.js:354:14)\\n    at param (/usr/src/app/node_modules/express/lib/router/index.js:365:14)\\n    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:410:3)\\n    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)\\n    at Function.handle (/usr/src/app/node_modules/express/lib/router/index.js:174:3)\\n    at router (/usr/src/app/node_modules/express/lib/router/index.js:47:12)\\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\\n    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)\\n    at /usr/src/app/node_modules/express/lib/router/index.js:284:7\\n    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)\\n    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)\\n    at /usr/src/app/node_modules/body-parser/lib/read.js:130:5\\n    at invokeCallback (/usr/src/app/node_modules/raw-body/index.js:224:16)\\n    at done (/usr/src/app/node_modules/raw-body/index.js:213:7)\\n    at IncomingMessage.onEnd (/usr/src/app/node_modules/raw-body/index.js:273:7)\\n    at emitNone (events.js:86:13)\\n    at IncomingMessage.emit (events.js:188:7)\\n    at endReadableNT (_stream_readable.js:975:12)\\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)"}}' }
```
The problems seams to be here:
https://github.com/space-invoices/si-api-js-sdk/blob/fd8b964cf36ded2d6e743d2e5975e99b5d9e009f/lib/requestService.js#L30

What I found out is that when I modify the **json** value to **false** the request goes trough and I get a successful response.

**Comment by bostjanpisler** [comment]
@Caperious can you please make a pull request with fix so all requests with empty body have this property set to `false`.
